# Workflow to deploy and test Autocoder to the CI server
name: CI Script - Segmentator
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}
on:
  workflow_dispatch:
  push:
    paths:
    - '.github/workflows/CI_Autocoder.yml'
    - '.github/actions/**'
    - 'src/**'
    - 'requirements.txt'

env:
  DEPLOY_HOST: ${{ vars.OGD_STAGING_HOST }}
  PROJECT_DIR:                 ${{ vars.WSGI_PATH }}/${{ github.event.repository.name }}
  DEPLOY_DIR:                  ${{ vars.WSGI_PATH }}/${{ github.event.repository.name }}/${{ github.ref_name }}
  DEPLOY_URL:  ${{ vars.OGD_STAGING_HOST }}/wsgi-bin/${{ github.event.repository.name }}/${{ github.ref_name }}/app.wsgi

jobs:
  ci_deploy:
    name: CI Deploy of Segmentator
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}
      cancel-in-progress: true

    steps:

    - name: Announce deploy
      run: echo "Deploying to ${{ env.DEPLOY_URL }}"
    # 1. Local checkout & config
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Config File
      uses: ./.github/actions/Autocoder_config
      with:
          api_base: ${{ env.DEPLOY_DIR }}

    # 2. Build 

    # 3. Remote config & deploy
    - name: Connect to VPN
      uses: opengamedata/actions-openconnect-vpn@v1.1
      with:
        username: ${{ secrets.VPN_USER }}
        password: ${{ secrets.VPN_PASS }}
        endpoint: "soe.vpn.wisc.edu"

    - name: Setup Access Key
      run: |
        mkdir -p ~/.ssh
        echo '${{ secrets.DEPLOY_KEY }}' >> ./key.txt
        chmod 600 ./key.txt
    - name: Ensure directory exists
      run: ssh -o StrictHostKeyChecking=no -T -i ./key.txt ${{ secrets.DEPLOY_USER }}@${{ env.DEPLOY_HOST }} "mkdir -p ${{ env.DEPLOY_DIR }}"

    - name: Upload to web server via rsync
      uses: burnett01/rsync-deployments@7.0.1
      with:
        # switches:
        # -v : verbose output
        # -r : recurse into subdirectories
        # -c : use checksum to determine what files to update/skip
        # -t : preserve modification times
        # --delete : delete extraneous files from destination directories
        # --exclude-from : skip any files in rsync-exclude
        # --chmod : For each directory (D) and file (F), give user (u) and group (g) rwx permissions.
        #           Give others (o) only read permissions, plus execute for directories.
        switches: -vrct --delete --exclude-from 'rsync-exclude' --chmod=Du=rwx,Dg=rwx,Do=rx,Fu=rwx,Fg=rwx,Fo=r
        path: ./src/*
        remote_path: ${{ env.DEPLOY_DIR }}
        remote_host: ${{ env.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key:  ${{ secrets.DEPLOY_KEY  }}

    - name: Upload uv.lock
      run: scp -o StrictHostKeyChecking=no -T -i ./key.txt ./uv.lock ${{ secrets.DEPLOY_USER }}@${{ env.DEPLOY_HOST }}:${{ env.DEPLOY_DIR }}
    - name: Upload pyproject.toml
      run: scp -o StrictHostKeyChecking=no -T -i ./key.txt ./pyproject.toml ${{ secrets.DEPLOY_USER }}@${{ env.DEPLOY_HOST }}:${{ env.DEPLOY_DIR }}

    - name: Set up venv for the deploy
      run: ssh -o StrictHostKeyChecking=no -T -i ./key.txt ${{ secrets.DEPLOY_USER }}@${{ env.DEPLOY_HOST }} "cd ${{ env.DEPLOY_DIR }}; python -m uv venv; python -m uv sync --no-dev --cache-dir ${{ env.PROJECT_DIR }}/.cache"

    - name: Setup uploads folder
      # Parts of the ssh multiline:
      # a. `! [ -d ${{ env.DEPLOY_DIR }}/uploads ]`                         : checks if the uploads directory already exists
      # b. `mkdir -p ${{ env.DEPLOY_DIR }}/uploads`                         : if directory didn't exist, (a) returns true, and we create it
      # c. `chgrp ${{ secrets.EXEC_GROUP }} ${{ env.DEPLOY_DIR }}/uploads/` : if (b) ran, then change group to the execution group
      # d. `chmod g+rwx ${{ env.DEPLOY_DIR }}/uploads/"`                    : if (c) ran, then ensure group has read, write, & exec on the uploads
      run: >
        ssh -o StrictHostKeyChecking=no -T
        -i ./key.txt
        ${{ secrets.DEPLOY_USER }}@${{ env.DEPLOY_HOST }}
        "! [ -d ${{ env.DEPLOY_DIR }}/uploads ] && mkdir -p ${{ env.DEPLOY_DIR }}/uploads && sudo chgrp ${{ secrets.EXEC_GROUP }} ${{ env.DEPLOY_DIR }}/uploads/ && sudo chmod g+rwx ${{ env.DEPLOY_DIR }}/uploads/"

    # 4. Cleanup & complete
    - name: Restart httpd via ssh
      run: ssh -o StrictHostKeyChecking=no -T -i ./key.txt ${{ secrets.DEPLOY_USER }}@${{ env.DEPLOY_HOST }} "sudo systemctl restart apache2"
